# numpy

In [1]:
import numpy as np

#numpy's main datatype is ndarray

In [25]:
a1=np.array([[[[[1,2,3]]]]])
a1.ndim

5

In [11]:
a1.dtype

dtype('int32')

In [24]:
a2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a2.shape)
print(a2.ndim)


(1, 3, 3)
3


In [2]:
a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             
            [[10,11,12],
            [13,14,15],
            [16,17,18]]])
a3.ndim

3

In [5]:
import pandas as pd;
df=pd.DataFrame(a3)
df

ValueError: Must pass 2-d input. shape=(2, 3, 3)

In [3]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
a4=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a4.shape)
print(a4.ndim)

(3, 3)
2


In [28]:
a5=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a5.shape)
print(a5.ndim)

(1, 3, 3)
3


# creating numpy array

In [6]:
data=np.array([1,2,3])
data

array([1, 2, 3])

In [7]:
data.dtype

dtype('int32')

In [8]:
ones=np.ones((2,3))   #shift + tab for overview of function
#by default it  takes float values

In [9]:
ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
ones.dtype

dtype('float64')

In [11]:
type(ones)

numpy.ndarray

In [12]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
range_array=np.arange(0,10,2) #np.arange( start,stop(not including),step)
range_array

array([0, 2, 4, 6, 8])

# np.random.randint

In [4]:
#np.randdom.randint
#randint(low, high=None, size=None, dtype=int)
import numpy as np
random_array=np.random.randint(0,10,size=(3,5))  #(low,high,size,dtype)  by default dtype is int
print(random_array)
print(random_array.dtype)
print("_____________________________")
print(type(random_array))

print("_____________________________")
print(np.size(random_array))
#or
print("_____________________________")
print(random_array.size)

[[5 0 2 3 5]
 [7 5 0 9 1]
 [9 9 1 9 2]]
int32
_____________________________
<class 'numpy.ndarray'>
_____________________________
15
_____________________________
15


In [5]:
random_array=np.random.randint(size=(2,3))  #(low,high,size,dtype)  by default dtype is int
print(random_array)
print(random_array.dtype)
print("_____________________________")
print(type(random_array))

print("_____________________________")
print(np.size(random_array))
#or
print("_____________________________")
print(random_array.size)

TypeError: randint() takes at least 1 positional argument (0 given)

In [6]:
random_array=np.random.randint(8,size=(3,5))  #(low,high,size,dtype)  by default dtype is int
print(random_array)
print(random_array.dtype)                     #by default lower is 0
print("_____________________________")
print(type(random_array))

print("_____________________________")
print(np.size(random_array))
#or
print("_____________________________")
print(random_array.size)

[[6 2 4 7 7]
 [7 6 3 1 0]
 [2 6 6 7 4]]
int32
_____________________________
<class 'numpy.ndarray'>
_____________________________
15
_____________________________
15


In [8]:
random_array=np.random.randint(0,size=(3,5))  #(low,high,size,dtype)  by default dtype is int
print(random_array)
print(random_array.dtype)                     #by default lower is 0
print("_____________________________")
print(type(random_array))

print("_____________________________")
print(np.size(random_array))
#or
print("_____________________________")
print(random_array.size)

ValueError: low >= high

# np.random.random

In [28]:
#np.randdom.random
#random(size=None)
random_array_2=np.random.random((5,3))
print(random_array_2)

[[0.50049882 0.48279888 0.81501715]
 [0.18759516 0.11078065 0.30903767]
 [0.91684674 0.30140897 0.933151  ]
 [0.43606089 0.35814109 0.40898912]
 [0.23605075 0.60509815 0.93333206]]


In [29]:
random_array_2=np.random.random()

#random(size=None)
#Return random floats in the half-open interval [0.0, 1.0)

print(random_array_2)

0.16575795971764373


# np.randdom.rand

In [32]:
#np.randdom.rand
#rand(d0, d1, ..., dn)
random_array_2=np.random.rand(5,3)
print(random_array_2)

[[0.84257874 0.38026297 0.08391641]
 [0.09685582 0.88556584 0.70602243]
 [0.24619922 0.66464557 0.13497887]
 [0.74496272 0.29824541 0.48820986]
 [0.21565991 0.45382124 0.47410395]]


In [34]:
random_array_2=np.random.rand((5,3))
print(random_array_2)

TypeError: 'tuple' object cannot be interpreted as an integer

# np.random.seed()

In [9]:
#sudo-random number
random_array=np.random.randint(10,size=(3,4))   #randint(low, high=None, size=None, dtype=int)
random_array
#every time we get new random data
#but we can stope it by using seed() function

array([[0, 6, 6, 7],
       [4, 9, 6, 6],
       [0, 8, 6, 1]])

In [24]:
#sudo-random number
np.random.seed(0)    #seed(self, seed=None)
random_array=np.random.randint(5,size=(3,4))   #randint(low, high=None, size=None, dtype=int)
random_array
#now we get same value even after runing it several time
#beacuse of seed()

array([[4, 0, 3, 3],
       [3, 1, 3, 2],
       [4, 0, 0, 4]])

In [1]:
#sudo-random number
import numpy as np
np.random.seed(seed=0)    #seed(self, seed=None)
random_array4=np.random.randint(10,size=(3,4))  #randint(low, high=None, size=None, dtype=int)
random_array4
#now we get same value even after runing it several time
#beacuse of seed()

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [20]:
#sudo-random number
np.random.seed(0,seed=0)    #seed(self, seed=None)
random_array4=np.random.randint(10,size=(3,4))
random_array4
#now we get same value even after runing it several time
#beacuse of seed()

TypeError: seed() got multiple values for keyword argument 'seed'

In [23]:
#random(size=None)
np.random.seed(7)
random_array_5=np.random.random((5,3))  #random(size=None)
print(random_array_5)

[[0.07630829 0.77991879 0.43840923]
 [0.72346518 0.97798951 0.53849587]
 [0.50112046 0.07205113 0.26843898]
 [0.4998825  0.67923    0.80373904]
 [0.38094113 0.06593635 0.2881456 ]]


#  some fun with numpy

In [40]:
a=np.array([1,2,3],dtype=complex)
print (a)

[[1.+0.j 2.+0.j 3.+0.j]]


In [41]:
import numpy as np
a=np.array([[2,3,4],[1,2,3]])
print(a)
print(a.shape)
a.shape=(3,2)
print("shape of array after using a.shape")
print(a)

[[2 3 4]
 [1 2 3]]
(2, 3)
shape of array after using a.shape
[[2 3]
 [4 1]
 [2 3]]


In [42]:
import numpy as np
a=np.array([[2,3,4],[1,2,3]])
print(a)
print(a.shape)
a.shape=(-1)#or any negative value like -2,-22,-45
print("shape of array after using a.shape")
print(a)

[[2 3 4]
 [1 2 3]]
(2, 3)
shape of array after using a.shape
[2 3 4 1 2 3]


# i1=int 16  ,i2=int16    ,i4=int32   ,i8=int64   except these all error

In [55]:
import numpy as np
dt=np.dtype('i1')
dt

dtype('int8')

In [56]:
import numpy as np
dt=np.dtype('i2')
dt

dtype('int16')

In [58]:
import numpy as np
dt=np.dtype('i4')
dt

dtype('int32')

In [59]:
import numpy as np
dt=np.dtype('i8')
dt

dtype('int64')

# array([],ndmin=)

In [71]:
a=np.array([1,2,3],ndmin=3)
print (a)
print(a.ndim)

[[[1 2 3]]]
3


In [72]:
a=np.array([1,2,3],ndmin=2)
print (a)
print(a.ndim)

[[1 2 3]]
2


In [74]:
a=np.array([1,2,3],ndmin=1)
print (a)
print(a.ndim)

[1 2 3]
1


In [78]:
a=np.array([[1,2,3]],ndmin=1) #min array inpute dimension
print (a)
print(a.ndim)

[[1 2 3]]
2


In [ ]:
data=np.random.randn()