# viewing arrays and matrices

In [2]:
import numpy as np

In [3]:
random_array=np.random.randint(0,13,size=(5,3))
print(random_array)
np.unique(random_array)  ##############imp

[[ 5  0  2]
 [10 12  4]
 [ 7  0  7]
 [11  3  8]
 [ 8  3  8]]


array([ 0,  2,  3,  4,  5,  7,  8, 10, 11, 12])

In [2]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2.shape)
print(a2.ndim)
print(a2)

(3, 3)
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
a1=np.array([1,2,3])
print(a1.shape)
print(a1.ndim)
print(a1)

(3,)
1
[1 2 3]


In [3]:
a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             
            [[10,11,12],
            [13,14,15],
            [16,17,18]]])
print(a3.shape)
print(a3.ndim)
print(a3)

(2, 3, 3)
3
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [17]:
print("a1 1D___________________________")
print(" ")
print(a1)

print(" ")
print("a2 2D___________________________")
print(" ")
print(a2)

print(" ")
print("a3 3D___________________________")
print(" ")
print(a3)

a1 1D___________________________
 
[1 2 3]
 
a2 2D___________________________
 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
a3 3D___________________________
 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [13]:
a1[0]

1

In [16]:
a2[0]

array([1, 2, 3])

In [22]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [24]:
a3[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [25]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [31]:
a3[0] #[axis][row][columns]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a3[0][2]    #[axis][row][columns]

array([7, 8, 9])

In [35]:
a3[0][2][2]     #[axis][row][columns]

9

In [36]:
a3[0,2,2]       #[axis][row][columns]

9

In [39]:
a3[:0,:2,:2]    #[axis][row][columns]

array([], shape=(0, 2, 2), dtype=int32)

In [40]:
a3[:1,:2,:2]    #[axis][row][columns]

array([[[1, 2],
        [4, 5]]])

In [41]:
a3[:2,:2,:2]    #[axis][row][columns]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [46]:
a3[:2,:2,:2]     #[axis][row][columns]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [47]:
a3[:2,:2,:3]     #[axis][row][columns]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [48]:
a3[0:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [49]:
a3[1:2,:2,:2]

array([[[10, 11],
        [13, 14]]])

In [5]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [3]:
a4=np.random.randint(0,10,size=(2,3,4,5))
print(a4.shape)
print(a4.ndim)
a4

(2, 3, 4, 5)
4


array([[[[0, 9, 1, 4, 9],
         [0, 6, 7, 6, 7],
         [2, 0, 9, 0, 5],
         [7, 4, 0, 5, 5]],

        [[0, 2, 1, 5, 8],
         [7, 1, 4, 1, 4],
         [8, 8, 4, 7, 1],
         [1, 8, 5, 2, 3]],

        [[4, 2, 4, 8, 1],
         [9, 1, 3, 2, 4],
         [5, 7, 2, 7, 6],
         [1, 2, 9, 5, 6]]],


       [[[2, 7, 3, 7, 8],
         [3, 7, 2, 8, 4],
         [5, 0, 6, 4, 4],
         [8, 9, 0, 8, 9]],

        [[8, 2, 9, 9, 6],
         [1, 4, 5, 4, 9],
         [1, 0, 0, 5, 2],
         [6, 3, 2, 5, 5]],

        [[4, 2, 5, 8, 1],
         [9, 7, 5, 3, 2],
         [1, 5, 7, 5, 6],
         [0, 9, 5, 3, 1]]]])

##### 

In [4]:
a4[:1,:1,:1,:1]    # [axis][number of matrix in each axis][row][colum]

array([[[[0]]]])

In [7]:
a4[0][0][0][1]    #[axis][number of matrix in each axis][row][colum]

9

In [6]:
a4[0][1][0][0]

0

In [10]:
#get the first 4 numbers of the inner most arrays
a4[:,:,:,:3]

array([[[[0, 9, 1],
         [0, 6, 7],
         [2, 0, 9],
         [7, 4, 0]],

        [[0, 2, 1],
         [7, 1, 4],
         [8, 8, 4],
         [1, 8, 5]],

        [[4, 2, 4],
         [9, 1, 3],
         [5, 7, 2],
         [1, 2, 9]]],


       [[[2, 7, 3],
         [3, 7, 2],
         [5, 0, 6],
         [8, 9, 0]],

        [[8, 2, 9],
         [1, 4, 5],
         [1, 0, 0],
         [6, 3, 2]],

        [[4, 2, 5],
         [9, 7, 5],
         [1, 5, 7],
         [0, 9, 5]]]])

In [11]:
a4


array([[[[0, 9, 1, 4, 9],
         [0, 6, 7, 6, 7],
         [2, 0, 9, 0, 5],
         [7, 4, 0, 5, 5]],

        [[0, 2, 1, 5, 8],
         [7, 1, 4, 1, 4],
         [8, 8, 4, 7, 1],
         [1, 8, 5, 2, 3]],

        [[4, 2, 4, 8, 1],
         [9, 1, 3, 2, 4],
         [5, 7, 2, 7, 6],
         [1, 2, 9, 5, 6]]],


       [[[2, 7, 3, 7, 8],
         [3, 7, 2, 8, 4],
         [5, 0, 6, 4, 4],
         [8, 9, 0, 8, 9]],

        [[8, 2, 9, 9, 6],
         [1, 4, 5, 4, 9],
         [1, 0, 0, 5, 2],
         [6, 3, 2, 5, 5]],

        [[4, 2, 5, 8, 1],
         [9, 7, 5, 3, 2],
         [1, 5, 7, 5, 6],
         [0, 9, 5, 3, 1]]]])

In [12]:
a4[1:2,2:3,:1,:4]

array([[[[4, 2, 5, 8]]]])