###### import numpy as np
x=np.array([[1,5,6,7],[5,8,7,8]])
print(x)

In [4]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print(x.shape)
print(x.size)
print(type(x))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
<class 'numpy.ndarray'>


In [6]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x)
x.shape=(3,2)
print(x)
y=x.reshape(3,2)
print(y)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [7]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])

y=x.reshape(3,2)
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])

x.shape=(3,2)
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.resize(a,(10,12))
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4 5 6]]


In [13]:
import numpy as np
x=np.arange(-10,15,3)
print(x)

[-10  -7  -4  -1   2   5   8  11  14]


In [14]:
import numpy as np
x=np.arange(1,15,3)
print(x)

[ 1  4  7 10 13]


In [21]:
import numpy as np
x=np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
import numpy as np
x=np.arange(0,15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [19]:
import numpy as np
x=np.arange(15,58)
print(x)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57]


In [24]:
import numpy as np
x=np.arange(40)
print(x)
print('dimention of an array is:',x.ndim)
y=x.reshape(8,5)
print(y)
print('now dimention of an array is:',y.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
dimention of an array is: 1
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
now dimention of an array is: 2


In [1]:
import numpy as np
x=np.arange(40)
print(x)
print('dimention of an array is:',x.ndim)
y=x.reshape(4,5,3)
print(y)
print('now dimention of an array is:',y.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
dimention of an array is: 1


ValueError: cannot reshape array of size 40 into shape (4,5,3)

In [4]:
import numpy as np
x=np.arange(40)
print(x)
print('dimention of an array is:',x.ndim)
y=x.reshape(2,2,5,2)
print(y)
print('now dimention of an array is:',y.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
dimention of an array is: 1
[[[[ 0  1]
   [ 2  3]
   [ 4  5]
   [ 6  7]
   [ 8  9]]

  [[10 11]
   [12 13]
   [14 15]
   [16 17]
   [18 19]]]


 [[[20 21]
   [22 23]
   [24 25]
   [26 27]
   [28 29]]

  [[30 31]
   [32 33]
   [34 35]
   [36 37]
   [38 39]]]]
now dimention of an array is: 4


In [27]:
import numpy as np
x = np.array([1,2,3,4,5], dtype = np.float128)
print( x.itemsize)

AttributeError: module 'numpy' has no attribute 'float128'

In [28]:
import numpy as np
x = np.array([1,2,3,4,5], dtype = np.float128)
print( x.itemsize)

AttributeError: module 'numpy' has no attribute 'float128'

In [29]:
import numpy as np
x=np.array([11,12,13,14],dtype=np.float64)
print(x.itemsize)

8


In [30]:
import numpy as np
x = np.array([1,2,3,4,5], dtype = np.float16)
print( x.itemsize)

2


In [32]:
import numpy as np
x = np.empty([3,2], dtype = int,order='c')
print (x)



[[1 2]
 [3 4]
 [5 6]]


In [2]:
import numpy as np
x = np.empty([3,2], dtype = int,order='F')
print (x)



[[0 0]
 [0 0]
 [0 0]]


In [1]:
import numpy as np
x=np.zeros((5,7), dtype=np.int)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [2]:
import numpy as np
x=np.ones((12,16),dtype=int)
print(x)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [3]:
import numpy as np
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
import numpy as np
x=np.ones((12,16))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [9]:
import numpy as np
x=np.ones((12,16),int)
print(x)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [8]:
import numpy as np
x=[1,2,3,4,5,6,7,8]
y=np.asarray(x)
print(y)
z=list(y)
print(z)
print(type(y))
print(type(z))

[1 2 3 4 5 6 7 8]
[1, 2, 3, 4, 5, 6, 7, 8]
<class 'numpy.ndarray'>
<class 'list'>


In [9]:
import numpy as np
x=np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [10]:
import numpy as np
a=[[0,1,5],[0,5,4]]
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

15
[0 6 9]
[6 9]


In [11]:
import numpy as np
a=np.array([[0,1,2],[2,3,4]])
b=np.array([4,5,6])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.dot(a,b))

[[ 4  6  8]
 [ 6  8 10]]
[[-4 -4 -4]
 [-2 -2 -2]]
[[ 0  5 12]
 [ 8 15 24]]
[[0.         0.2        0.33333333]
 [0.5        0.6        0.66666667]]
[17 47]


In [3]:
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(np.amin(a,axis=1))# 0 for column 1 for row
print(np.amin(a,axis=0))
print(np.amax(a,axis=1))
print(np.amax(a,axis=0))

[3 3 2]
[2 4 3]
[7 8 9]
[8 7 9]


In [13]:
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(np.amin(a,axis=1))# 0 for column , 1 for row
print(np.amin(a,axis=0))
print(np.amax(a,axis=1))
print(np.amax(a,axis=0))
print(np.ptp(a))
print(np.ptp(a,axis=1))
print(np.ptp(a,axis=0))

[3 3 2]
[2 4 3]
[7 8 9]
[8 7 9]
7
[4 5 7]
[6 3 6]


In [14]:
import numpy as np
a= np.array([[30,65,70],[80,95,10],[50,90,60]])
print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a,axis=1))

65.0
[50. 90. 60.]
[65. 80. 60.]


In [15]:
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(np.mean(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.6666666666666665
[2.66666667 3.66666667 4.66666667]
[2. 4. 5.]


In [16]:
import numpy as np
print (np.std([1,2,3,4]))
print (np.var([1,2,3,4]))

1.118033988749895
1.25


In [17]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print( c)

[ 10  40  90 160]


In [1]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a + b
print( c)
print(np.add(a,b))

[11 22 33 44]
[11 22 33 44]


In [1]:
import numpy as np
import pandas as pd

In [11]:
a=np.arange(1,30,1)
#b=np.resize(a,(4,4))
c=np.reshape(a,(2,2))
print(c)

ValueError: cannot reshape array of size 29 into shape (2,2)

In [33]:
import numpy as np
data=np.arange(1,40,1)
data.resize(1,3,8)
print("data ")
print("*******************************")
print(data)

print(" ")
print("*******************************")
print(data[:,1])
print(" ")
print("*******************************")
print(data[:,1:5])
print(" ")
print("*******************************")
print(data[0:2,1:3])

data 
*******************************
[[[ 1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16]
  [17 18 19 20 21 22 23 24]]]
 
*******************************
[[ 9 10 11 12 13 14 15 16]]
 
*******************************
[[[ 9 10 11 12 13 14 15 16]
  [17 18 19 20 21 22 23 24]]]
 
*******************************
[[[ 9 10 11 12 13 14 15 16]
  [17 18 19 20 21 22 23 24]]]


In [38]:
import numpy as np
data=np.array([[[1,2,3,4,5,6,7,8],
               [9,10,11,12,13,14,15,16],
               [17,18,19,20,21,22,23,24]]])
print(data)

print(data[:,1])

[[[ 1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16]
  [17 18 19 20 21 22 23 24]]]
[[ 9 10 11 12 13 14 15 16]]
