In [2]:
import numpy as np
a=np.array([[2,3,4],[3,5,7]])
print(a)
print(a.shape)
print(a.size)


[[2 3 4]
 [3 5 7]]
(2, 3)
6


In [8]:
x=np.arange(0,20,0.5)
print(x)
print(x.size)
print(x.itemsize)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]
40
8


In [12]:
import numpy as np
a=np.array([[2,3,4],[3,5,7]])
b=np.array([[8,3,9],[7,5,7]])
print(np.add(a,b))
print(np.divide(a,b))
print(np.multiply(a,b))


[[10  6 13]
 [10 10 14]]
[[0.25       1.         0.44444444]
 [0.42857143 1.         1.        ]]
[[16  9 36]
 [21 25 49]]


In [13]:
import numpy as np
a=np.array([[2,8,4],[3,9,7]])
print("min..................")
print(np.amin(a,axis=0))
print(np.amin(a,axis=1))
print(np.amax(a,axis=0))
print(np.amax(a,axis=1))

[2 8 4]
[2 3]
[3 9 7]
[8 9]


In [14]:
import numpy as np
a=np.array([[2,8,4],[3,9,7]])
print("..................")
print(np.median(a))
print(np.median(a,axis=0))
print(np.median(a,axis=1))


..................
5.5
[2.5 8.5 5.5]
[4. 7.]


In [16]:
import pandas as pd
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
print(df)

print("*************************************************************************")
# Adding a new column to an existing DataFrame object with column label by passing new series
print ("Adding a new column by passing as Series:")
df['three']=pd.Series([10,20,30],index=['a','b','c'])
print (df)

print("*************************************************************************")
print ("Adding a new column using the existing columns in DataFrame:")
df['four']=df['one']+df['three']
print (df)

print("*************************************************************************")
print ("Adding a new column using the existing columns in DataFrame:")
df['five']=df['one']*df['three']
print (df)


   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4
*************************************************************************
Adding a new column by passing as Series:
   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
*************************************************************************
Adding a new column using the existing columns in DataFrame:
   one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN
*************************************************************************
Adding a new column using the existing columns in DataFrame:
   one  two  three  four  five
a  1.0    1   10.0  11.0  10.0
b  2.0    2   20.0  22.0  40.0
c  3.0    3   30.0  33.0  90.0
d  NaN    4    NaN   NaN   NaN
